# Generated by Django 4.0 on 2021-12-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_shopimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopimage',
            options={'verbose_name': 'Изображение магазина', 'verbose_name_plural': 'Изображения магазинов'},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='price',
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='telephone',
            field=models.CharField(max_length=50, verbose_name='Телефон магазина'),
        ),
    ]
