# Generated by Django 4.0 on 2022-01-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopimage',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
