# Generated by Django 4.0 on 2022-01-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productimage_images_alter_shopimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
