# Generated by Django 4.0 on 2022-01-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='activate',
            new_name='active',
        ),
    ]
